### ISSUE TITLE
Glitched chunks (LATEST COMMIT)

### ISSUE THREAD

**Issue by sgdc3** [timvisee/DungeonMaze#38]
![2015-03-28_21 17 53](https://cloud.githubusercontent.com/assets/8779252/6882728/f2a48132-d58f-11e4-8499-de8d79b8c575.png)

**Comment by timvisee** [comment]
Hello,

This issue is caused by Minecraft itself, and can't really be solved as far as I know. There isn't a workaround for this issue yet. The problem is possibly that chunk data being send to the client is corrupted and thus the chunk is kept unloaded on the client side. The chunks should be loading perfectly fine once you logout and login again.

So, these chunks are generated perfectly fine, but it's an issue on Minecraft's side that is causing the chunks being kept unloaded on the client side.

Tim Visée

**Comment by sgdc3** [comment]
Ah Ok ;)
